version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      gradle:
        patterns:
          - "*"
