apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-ur-ekstern-api
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 12m
      memory: 256Mi
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/metrics
  accessPolicy:
    inbound:
      rules:
        - application: ytelser-rest-proxy
          namespace: team-emottak
          cluster: prod-fss
    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
        - ipv4: 155.55.1.78  # UR via zos-connect
          ports:
            - port: 9080
  azure:
    application:
      enabled: true
      claims:
        extra:
          - azp_name
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: "ytelser.read" # Scope: nav:reskontro/ytelser.read, subscope: reskontro/ytelser.read
          accessibleForAll: true
          delegationSource: altinn
          enabled: true
          separator: "/"
          product: "reskontro"
      consumes:
        - name: "nav:reskontro/ytelser.read"
  ingresses:
    - https://sokos-ur-ekstern-api.intern.nav.no
    - https://sokos-ur-ekstern-api.nav.no
  envFrom:
    - secret: sokos-ur-ekstern-api-secrets
  env:
    - name: UR_ENDPOINT_URL
      value: "https://155.55.1.78:9080"
