apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-ur-ekstern-api
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 2
    max: 2
  secureLogs:
    enabled: true
  resources:
    limits:
      cpu: 750m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 512Mi
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: "ytelser.read" # Scope: nav:reskontro:ytelser.read, subscope: reskontro:ytelser.read
          enabled: true
          product: "reskontro"
          consumers:
            - name: "NAV"
              orgno: "889640782"
            - name: "Husbanken"
              orgno: "942114184"
      consumes:
        - name: "nav:reskontro:ytelser.read"
  prometheus:
    enabled: true
    path: /internal/metrics
  ingresses:
    - https://sokos-ur-ekstern-api.ekstern.dev.nav.no
