openapi: 3.0.1
info:
  title: SOKOS UR ekstern-API
  description: Tjenestespesifikasjon for SOKOS UR ekstern API<p>Du når oss på Slack kanalen [\#po-utbetaling](https://nav-it.slack.com/archives/CKZADNFBP).
  version: 1.0.0
servers:
  - url: /ur-ekstern/api
tags:
  - name: ur-ekstern.v1
paths:
  /v1/finn-ytelser:
    post:
      tags:
        - ur-ekstern.v1
      summary: Finn ytelser (ekstern)
      operationId: finn-ytelser
      parameters:
        - in: header
          name: x-correlation-id
          required: true
          schema:
            type: string
            description: Corrolation id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ytelseoppslag'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mottaker'
                description: Liste over utbetalinger for den angitte id i den angitte
                  periode.
        401:
          description: Uautorisert
          content:
            text/plain:
              schema:
                type: string
                example: 'Unauthorized'
        403:
          description: Tilgang nektet
          content:
            text/plain:
              schema:
                type: string
                example: 'Forbidden'
        500:
          description: Intern server feil
          content:
            text/plain:
              schema:
                type: string
                example: 'Noe gikk galt'
components:
  schemas:
    Ytelseoppslag:
      required: [periode, mottakere]
      type: object
      properties:
        periode:
          $ref: '#/components/schemas/Periode'
        ytelseskoder:
          type: array
          minItems: 1
          items:
            type: string
            enum:
              - AAP
              - DAGPENGER
          description: |
            En liste med ytelsestyper som det skal søkes på. Dersom ingen er vedlagt får man alle man har tilgang på.
        mottakere:
          type: array
          maxItems: 1000
          items:
            type: string
          description: |
            En liste med unike identer for mattaker av ytelser, f.eks fødselsnummer.
    Mottaker:
      type: object
      description: Informasjon om en utbetaling som er gjort.
      required: [mottakerId, ytelser]
      properties:
        mottakerId:
          type: string
        ytelser:
          type: array
          items:
            $ref: '#/components/schemas/Ytelse'
    Ytelse:
      type: object
      description: Informasjon om en utbetaling som er gjort.
      required:
        - datoPostert
        - datoValutert
        - rettighetshaver
        - ytelse
        - ytelseBeskrivelse
        - ytelsePeriode
        - belop
      properties:
        datoPostert:
          type: string
          format: date
        datoValutert:
          type: string
          format: date
        rettighetshaver:
          type: string
        ytelse:
          type: string
        ytelseBeskrivelse:
          type: string
        ytelsePeriode:
          $ref: '#/components/schemas/Periode'
        belop:
          type: number
          format: doubble
          example: 999.99
        typeUtbetaling:
          type: string
    Periode:
      type: object
      description: En periode angir et tidsintervall med fra-og-med og til-og-med.
      required: [fom, tom]
      properties:
        fom:
          type: string
          format: date
          description: Fra og med dato
        tom:
          type: string
          format: date
          description: Til og med dato

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
