name: Deploy alerts
on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'alerts.yaml'
      - '.nais/alerterator.yaml'
  workflow_dispatch:
jobs:
  apply-alerts-dev:
    name: Apply alerts to cluster dev-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ratchet:actions/checkout@v3
      - name: deploy to dev
        uses: nais/deploy/actions/deploy@12442ef9824a1f795d01e821f14962f7029c3723 # ratchet:nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/alerterator.yaml
  apply-alerts-prod:
    name: Apply alerts to cluster prod-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ratchet:actions/checkout@v3
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@12442ef9824a1f795d01e821f14962f7029c3723 # ratchet:nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/alerterator.yaml
