name: PR bygg og test

on:
  pull_request:

jobs:
  build-pr:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # ratchet:actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # ratchet:gradle/gradle-build-action@v3.5.0
        with:
          arguments: build shadowjar
