name: Build, push, and deploy

on:
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - '.github/workflows/alerts.yml'
      - '.nais/alerterator.yml'
      - '**.md'
  workflow_dispatch:

env:
  TZ: Europe/Oslo

jobs:
  build:
    permissions:
      contents: "write"
      id-token: "write"
    name: Build/test & push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/gradle-build-action@v2.9.0
        env: # Ekskluderer test dependencies
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: compileClasspath|runtimeClasspath
        with:
          dependency-graph: generate-and-submit
          arguments: build shadowJar
      - name: Push docker image to Google Artifact Registry
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          byosbom: dependency-graph-reports/build_push_and_deploy-build.json
          team: okonomi
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          tag: latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-dev:
    permissions:
      id-token: "write"
    name: Deploy to dev-gcp
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v2
        env:
          IMAGE: ${{ needs.build.outputs.image }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/naiserator-dev.yml
