name: PR bygg og test

on:
  pull_request:

jobs:
  build-pr:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # ratchet:actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # ratchet:actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # ratchet:gradle/gradle-build-action@v2.9.0
        with:
          arguments: build shadowjar
